<?php
namespace Lpp\Analysis;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-08 at 03:54:27.
 */
class UnirestAnalysisTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UnirestAnalysis
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UnirestAnalysis;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Lpp\Analysis\UnirestAnalysis::analyse
     * @todo   Implement testAnalyse().
     */
    public function testAnalyse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
